### ISSUE TITLE
Feedback on the ESP32 SVD file

### ISSUE THREAD

**Issue by aykevl** [espressif/svd#14]
I've tried switching TinyGo to use the new official SVD file, and of course there are differences with the community version :)
Here is what I found:

* The registers `FUNC%s_IN_SEL_CFG` have the fields `FUNC_IN_SEL`, `FUNC_IN_INV_SEL`, and `SIG_IN_SEL`. That's a bit of repetition. Maybe that's entirely intended, but this repetition wasn't there in the community version of the SVD file (which had fields named `SEL`, `IN_INV_SEL`, and `IN_SEL`). (Feel free to ignore this as "works as intended").
* I think the IO_MUX pins are incorrect. Right now there is the `GPIO%s` array of registers address 0x3FF49044, which is correct for GPIO0, but is already incorrect for GPIO1 (aka U0TXD) which lives at address 0x3FF49088. I wish these registers were in some sort of logical order, but for the ESP32 this does not appear to be the case.
* The UART has the `FIFO_AHB` register according to the SVD file, which would be the `UART_FIFO_REG` according to the reference manual. I wonder why there is a _AHB suffix? It isn't there in the SVD file for the ESP32-C3.
* There is a peripheral named `RTCCNTL` with a group name of `RTC_CNTL`? That seems odd. In the ESP32-C3 it's just called `RTC_CNTL`.
* The `SOC_CLK_SEL` field of the RTC_CNTL register does not have names for the various clock sources (XTAL, PLL, CK8M, APLL). Maybe this is missing from the data? It was there in the community version of the SVD, which was nice. If it's not in the data, it's not a big loss to write these constants manually. (The same holds true for many other register fields).

Not all of these are necessarily bugs, but some seem to be.

**Comment by jessebraham** [comment]
I have be preoccupied with some other projects the last few weeks here, so not a lot of progress on this yet. Sorry about that.

I did push a new release of the SVD which includes a number of small fixes. Relevant to this issue:

- the `FUNC_IN_SEL`, `FUNC_IN_INV_SEL`, and `SIG_IN_SEL` registers have been renamed to `SEL`, `IN_INV_SEL`, and `SIG_SEL` respectively
- the `GPIO%s` pins have been broken out in to separate registers rather than being collected in an array
- the `RTCCNTL` peripheral has been renamed to `RTC_CNTL`

I will hopefully get to the remaining issues in the coming weeks.

**Comment by jessebraham** [comment]
Apologies for taking so long to get back to this (again). With the exception of the `SOC_CLK_SEL` field's enums, I believe everything else in here should be resolved. I do plan on adding field enum support to the SVD generator at some point, I just haven't had a chance yet unfortunately.

If you feel this has not been resolved please feel free to re-open this issue, or to open a new one.

**Comment by jessebraham** [comment]
I actually managed to get `enumeratedValues` support added to our SVD generator today, so the next release will include these for at least some registers.
